name: 'Branch PR Sync Base'
description: 'Sync branches from a specified base branch (default: main) into open PRs.'
inputs:
  dry_run:
    description: 'If true, logs actions without merging/pushing.'
    required: false
    default: 'false'
  base_branch:
    description: 'The base branch for the sync operation (e.g., main, develop).'
    required: false
    default: 'main'
  require_auto_merge:
    description: 'Only sync PRs with auto-merge enabled.'
    required: false
    default: 'true'
  author_name:
    description: 'Git author name for the commit.'
    required: false
    default: 'github-actions'
  author_email:
    description: 'Git author email for the commit.'
    required: false
    default: 'github-actions@github.com'
  commit_message:
    description: 'Custom commit message for the sync commit.'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Merge base into PR branches
      uses: ./github/workflows/sync-main-into-prs.yml
      with:
        dry_run: ${{ inputs.dry_run }}
        base_branch: ${{ inputs.base_branch }}
        require_auto_merge: ${{ inputs.require_auto_merge }}
        author_name: ${{ inputs.author_name }}
        author_email: ${{ inputs.author_email }}
        commit_message: ${{ inputs.commit_message }}
