name: Always Passing Status Check

on:
  pull_request:
    branches: 
        - 'main'

jobs:
  always-pass:
    runs-on: ubuntu-latest
    steps:
      - name: Always Pass
        run: echo "✅ This status check always passes."