name: Trigger Sync PRs Workflow

on:
  push:
    branches:
      - main

jobs:
  trigger-sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Branch PR Sync Base Action
        uses: mizx/branch-pr-sync-base@main
        with:
          base_branch: main
          dry_run: false
          require_auto_merge: false
          github_token: ${{ secrets.GITHUB_TOKEN }}
