name: Trigger Sync PRs Workflow

on:
  push:
    branches:
      - main

jobs:
  trigger-sync:
    uses: ./.github/workflows/sync-main-into-prs.yaml
    with:
        base_branch: main
        dry_run: true
        require_auto_merge: true
